### ISSUE TITLE
Handle dir not found exception in dir_files

### ISSUE THREAD

**Issue by julianmorley** [sul-dlss-labs/OCFL-Tools#73]
If you ask `ocfl_validator#verify_manifest` to check a directory that doesn't exist, it has problems!

Verify_manifest should capture this as an error (and add it to the results object) without crashing.

```
Traceback (most recent call last):
	4: from ./test-fixtures.rb:9:in `<main>'
	3: from /Users/jmorley/.rvm/gems/ruby-2.5.1/gems/ocfl-tools-0.9.3/lib/ocfl_tools/ocfl_validator.rb:118:in `verify_manifest'
	2: from /Users/jmorley/.rvm/gems/ruby-2.5.1/gems/ocfl-tools-0.9.3/lib/ocfl_tools/utils_file.rb:43:in `get_versions_dir_files'
	1: from /Users/jmorley/.rvm/gems/ruby-2.5.1/gems/ocfl-tools-0.9.3/lib/ocfl_tools/utils_file.rb:31:in `get_version_dir_files'
/Users/jmorley/.rvm/gems/ruby-2.5.1/gems/ocfl-tools-0.9.3/lib/ocfl_tools/utils_file.rb:10:in `get_dir_files': Directory does not exist! (RuntimeError)
```

**Comment by julianmorley** [comment]
Fixed by https://github.com/sul-dlss-labs/OCFL-Tools/pull/74
